name: flutter_qiblah
description: Flutter Qiblah is a package that allows you to display Qiblah direction in you app with support for both Android and iOS
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 3.1.0
homepage: https://github.com/nafiskabbo/flutter_qiblah_v2

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^12.0.0
  stream_transform: ^2.1.0
  vector_math: ^2.1.4
  flutter_compass_v2:
    git:
      url: https://github.com/nafiskabbo/flutter_compass_v2.git
      ref: master # branch name

dependency_overrides:
  meta: ^1.15.0

flutter:
  plugin:
    platforms:
      android:
        package: ml.medyas.flutter_qiblah
        pluginClass: FlutterQiblahPlugin
      ios:
        pluginClass: FlutterQiblahPlugin
